export const SEND_MESSAGE = 'SEND_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const START_CHAT = 'START_CHAT';
export const CHAT_STARTED = 'CHAT_STARTED';
export const RETRIEVE_CHATS = 'RETRIEVE_CHATS';
